x-histoseg-common: &histoseg-common
  image: histoseg-plugin:dev
  environment:
    HISTOSEG_CONFIG: /app/config/settings-dev.yaml
    HOME: /app
    HF_HOME: /app/.cache/huggingface
  working_dir: /app
  user: "${UID}:${GID}"
  restart: unless-stopped
  shm_size: "8gb"
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]


services:
  api:
    <<: *histoseg-common
    build:
      context: /home/val/workspaces
      dockerfile: histoseg-plugin/Dockerfile
    container_name: histoseg-api
    command: >
      uvicorn histoseg_plugin.api.main:create_app --factory --host 0.0.0.0 --port 8000
    ports:
      - "8090:8000"
      - "5679:5678"

  worker:
    <<: *histoseg-common
    container_name: histoseg-worker
    command: python -m histoseg_plugin.jobs.worker_main
    ports:
      - "5678:5678"